# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: S:/univer/sem2_1/digital_experiment/exp_6/Lab6_xterm/Lab6_xterm.srcs/sources_1/ip/vga_mem/vga_mem.xci
# IP: The module: 'vga_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/univer/sem2_1/digital_experiment/exp_6/Lab6_xterm/Lab6_xterm.gen/sources_1/ip/vga_mem/vga_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: S:/univer/sem2_1/digital_experiment/exp_6/Lab6_xterm/Lab6_xterm.srcs/sources_1/ip/vga_mem/vga_mem.xci
# IP: The module: 'vga_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/univer/sem2_1/digital_experiment/exp_6/Lab6_xterm/Lab6_xterm.gen/sources_1/ip/vga_mem/vga_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
